# Docker Compose for Playground - Secure Configuration
version: '3.8'

services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground-container
    restart: unless-stopped
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Network configuration
    ports:
      - "8000:8000"
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    
    # Volumes for temporary files (since container is read-only)
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/run:rw,noexec,nosuid,size=50m
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: playground-network
    driver: bridge
